"""
Event Impact Predictor — Gridlock 2.0 Round 2
Predicts spatial-temporal traffic impact of events on Bengaluru's road network.
Uses the junction topology and event type templates to model congestion propagation.
"""

import math
import numpy as np
from datetime import datetime, timedelta
from engine.bengaluru_kb import JUNCTIONS, VENUES, EVENT_TYPES, get_nearby_junctions


def _time_decay_factor(distance_km, max_radius_km):
    """Exponential distance decay — junctions further from event are less affected."""
    if max_radius_km <= 0:
        return 0.0
    normalized = distance_km / max_radius_km
    return max(0.0, math.exp(-2.5 * normalized))


def _hour_load_profile(hour):
    """
    Bengaluru's typical hourly traffic load profile (0-23).
    Based on ASTraM traffic count data patterns.
    Returns a multiplier [0.1, 1.0] representing relative road load.
    """
    profiles = {
        0: 0.10, 1: 0.08, 2: 0.06, 3: 0.05, 4: 0.07, 5: 0.15,
        6: 0.30, 7: 0.55, 8: 0.85, 9: 0.95, 10: 0.80, 11: 0.70,
        12: 0.65, 13: 0.60, 14: 0.65, 15: 0.70, 16: 0.80, 17: 0.95,
        18: 1.00, 19: 0.90, 20: 0.75, 21: 0.55, 22: 0.35, 23: 0.20,
    }
    return profiles.get(int(hour) % 24, 0.5)


def predict_event_impact(event_type, venue_id, event_date, event_time,
                          expected_crowd=None, custom_lat=None, custom_lon=None):
    """
    Core prediction engine.
    
    Args:
        event_type: Key from EVENT_TYPES (e.g., 'ipl_match')
        venue_id: Key from VENUES (e.g., 'chinnaswamy')
        event_date: Date string 'YYYY-MM-DD'
        event_time: Time string 'HH:MM' (24hr)
        expected_crowd: Override venue default crowd size
        custom_lat/lon: For custom venue location
    
    Returns:
        dict with full impact analysis
    """
    # Resolve event template
    event_template = EVENT_TYPES.get(event_type)
    if not event_template:
        raise ValueError(f"Unknown event type: {event_type}")
    
    # Resolve venue
    venue = VENUES.get(venue_id, VENUES["custom"])
    if venue_id == "custom" and custom_lat and custom_lon:
        venue = {**venue, "lat": custom_lat, "lon": custom_lon}
    
    # Parse timing
    try:
        event_dt = datetime.strptime(f"{event_date} {event_time}", "%Y-%m-%d %H:%M")
    except ValueError:
        event_dt = datetime.now().replace(hour=18, minute=0, second=0)
    
    event_hour = event_dt.hour
    event_day_name = event_dt.strftime("%A")
    is_weekend = event_dt.weekday() >= 5
    
    # Crowd estimation
    if expected_crowd and expected_crowd > 0:
        crowd = expected_crowd
    else:
        crowd = int(venue.get("capacity", 10000) * event_template["peak_crowd_factor"])
    
    # Calculate vehicles generated by event
    vehicles_generated = int(crowd * event_template["vehicle_ratio"] / 2.5)  # 2.5 avg occupancy
    
    # Impact radius
    impact_radius = event_template["impact_radius_km"]
    # Scale radius with crowd size
    crowd_scale = min(2.0, max(1.0, crowd / 20000))
    adjusted_radius = impact_radius * crowd_scale
    
    # Find affected junctions
    affected_junctions = get_nearby_junctions(
        venue["lat"], venue["lon"], adjusted_radius
    )
    
    # Calculate per-junction impact
    junction_impacts = []
    total_delayed_vehicles = 0
    total_delay_person_hours = 0
    
    for jid, dist_km in affected_junctions:
        jdata = JUNCTIONS[jid]
        
        # Base congestion from event
        decay = _time_decay_factor(dist_km, adjusted_radius)
        base_load = _hour_load_profile(event_hour)
        
        # Weekend factor — less baseline traffic but event crowds still come
        weekend_factor = 0.75 if is_weekend else 1.0
        
        # Congestion multiplier at this junction
        event_congestion = event_template["congestion_multiplier"] * decay
        total_congestion = (base_load * weekend_factor) + event_congestion
        
        # Capacity overflow — 80% of event vehicles pass through nearby junctions
        normal_vehicles = int(jdata["base_capacity"] * base_load * weekend_factor)
        event_vehicles = int(vehicles_generated * decay * 0.80)
        total_vehicles = normal_vehicles + event_vehicles
        capacity_ratio = total_vehicles / jdata["base_capacity"]
        
        # Delay estimation using Modified BPR function
        # Real-world calibration: Bengaluru junctions experience severe delays
        # even at moderate V/C ratios due to signal cycles, pedestrian interference, autos
        free_flow_min = 3.0  # Avg signal cycle crossing time at a junction
        alpha, beta = 0.9, 4.5  # Calibrated for Indian mixed-traffic conditions
        
        # BPR delay component
        bpr_delay = free_flow_min * alpha * max(0, capacity_ratio ** beta - 1)
        
        # Proximity surge delay — events cause additional friction (pedestrians,
        # parking searches, police checks) independent of V/C ratio
        proximity_delay = event_template["congestion_multiplier"] * decay * 8.0  # up to ~15 min for nearest
        
        delay_min = bpr_delay + proximity_delay
        delay_min = min(delay_min, 90.0)  # Cap at 90 minutes
        
        # Without any deployment, the delay is the raw prediction
        without_deployment_delay = delay_min
        
        # With optimal deployment, estimate reduction
        # Deployment effectiveness: signal override + constables + diversions
        deployment_effectiveness = 0.0
        if event_template["signal_override_needed"]:
            deployment_effectiveness += 0.20   # 20% reduction from signal timing
        deployment_effectiveness += min(0.25, decay * 0.30)  # Constable effectiveness
        deployment_effectiveness += 0.15  # Diversion route effectiveness
        deployment_effectiveness = min(deployment_effectiveness, 0.60)  # Max 60% reduction
        
        with_deployment_delay = without_deployment_delay * (1 - deployment_effectiveness)
        
        # Aggregate stats
        delayed_vehicles = int(total_vehicles * min(1.0, delay_min / 30.0))
        total_delayed_vehicles += delayed_vehicles
        total_delay_person_hours += (delayed_vehicles * 2.5 * delay_min / 60.0)  # 2.5 people per vehicle
        
        # Severity classification — use combined delay + capacity ratio
        combined_score = capacity_ratio * 0.4 + (delay_min / 15.0) * 0.6
        if combined_score > 1.8 or capacity_ratio > 1.8:
            severity = "CRITICAL"
            color = "#ff1744"
        elif combined_score > 1.2 or capacity_ratio > 1.4:
            severity = "HIGH"
            color = "#ff6d00"
        elif combined_score > 0.6 or capacity_ratio > 1.0:
            severity = "MODERATE"
            color = "#ffd600"
        else:
            severity = "LOW"
            color = "#00e676"
        
        # Constables needed (above normal)
        extra_constables = 0
        if severity == "CRITICAL":
            extra_constables = max(4, int(6 * decay))
        elif severity == "HIGH":
            extra_constables = max(2, int(4 * decay))
        elif severity == "MODERATE":
            extra_constables = max(1, int(2 * decay))
        
        junction_impacts.append({
            "junction_id": jid,
            "name": jdata["name"],
            "lat": jdata["lat"],
            "lon": jdata["lon"],
            "zone": jdata["zone"],
            "distance_km": round(dist_km, 2),
            "normal_vehicles_hr": normal_vehicles,
            "event_vehicles_hr": event_vehicles,
            "total_vehicles_hr": total_vehicles,
            "capacity": jdata["base_capacity"],
            "capacity_ratio": round(capacity_ratio, 2),
            "congestion_multiplier": round(total_congestion, 2),
            "delay_without_deployment_min": round(without_deployment_delay, 1),
            "delay_with_deployment_min": round(with_deployment_delay, 1),
            "severity": severity,
            "color": color,
            "typical_constables": jdata["typical_constables"],
            "extra_constables_needed": extra_constables,
            "total_constables": jdata["typical_constables"] + extra_constables,
            "road_type": jdata["road_type"],
            "impact_decay": round(decay, 3),
        })
    
    # Sort by severity (CRITICAL first)
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2, "LOW": 3}
    junction_impacts.sort(key=lambda x: (severity_order.get(x["severity"], 4), -x["impact_decay"]))
    
    # Timeline windows
    pre_start = event_dt - timedelta(hours=event_template["pre_event_surge_hours"])
    post_end = event_dt + timedelta(hours=event_template["duration_hours"] + event_template["post_event_surge_hours"])
    
    # Generate hourly timeline
    timeline = []
    current = pre_start.replace(minute=0)
    while current <= post_end:
        hours_from_event = (current - event_dt).total_seconds() / 3600
        
        if hours_from_event < -event_template["pre_event_surge_hours"]:
            phase = "Normal"
            load_factor = 0.3
        elif hours_from_event < 0:
            phase = "Pre-Event Surge"
            progress = 1.0 - abs(hours_from_event) / event_template["pre_event_surge_hours"]
            load_factor = 0.3 + 0.7 * progress
        elif hours_from_event < event_template["duration_hours"]:
            phase = "Event Active"
            load_factor = 1.0
        elif hours_from_event < event_template["duration_hours"] + event_template["post_event_surge_hours"]:
            phase = "Post-Event Dispersal"
            progress = (hours_from_event - event_template["duration_hours"]) / event_template["post_event_surge_hours"]
            load_factor = 1.0 - 0.7 * progress
        else:
            phase = "Normal"
            load_factor = 0.3
        
        timeline.append({
            "time": current.strftime("%H:%M"),
            "phase": phase,
            "load_factor": round(load_factor, 2),
            "congestion_level": round(load_factor * event_template["congestion_multiplier"], 2),
        })
        current += timedelta(hours=1)
    
    # Overall summary
    avg_delay_without = np.mean([j["delay_without_deployment_min"] for j in junction_impacts]) if junction_impacts else 0
    avg_delay_with = np.mean([j["delay_with_deployment_min"] for j in junction_impacts]) if junction_impacts else 0
    total_extra_constables = sum(j["extra_constables_needed"] for j in junction_impacts)
    critical_count = sum(1 for j in junction_impacts if j["severity"] == "CRITICAL")
    high_count = sum(1 for j in junction_impacts if j["severity"] == "HIGH")
    
    return {
        "event": {
            "type": event_type,
            "type_name": event_template["name"],
            "icon": event_template["icon"],
            "venue": venue["name"],
            "venue_id": venue_id,
            "venue_lat": venue["lat"],
            "venue_lon": venue["lon"],
            "date": event_date,
            "time": event_time,
            "day_name": event_day_name,
            "is_weekend": is_weekend,
            "expected_crowd": crowd,
            "vehicles_generated": vehicles_generated,
            "duration_hours": event_template["duration_hours"],
            "impact_radius_km": round(adjusted_radius, 1),
            "predictability": event_template["predictability"],
            "barricade_type": event_template["barricade_type"],
            "signal_override_needed": event_template["signal_override_needed"],
        },
        "impact_summary": {
            "affected_junctions": len(junction_impacts),
            "critical_junctions": critical_count,
            "high_junctions": high_count,
            "avg_delay_without_deployment_min": round(avg_delay_without, 1),
            "avg_delay_with_deployment_min": round(avg_delay_with, 1),
            "delay_reduction_pct": round((1 - avg_delay_with / max(avg_delay_without, 0.1)) * 100, 1),
            "total_delayed_vehicles": total_delayed_vehicles,
            "total_delay_person_hours": round(total_delay_person_hours, 0),
            "total_extra_constables": total_extra_constables,
            "impact_window_start": pre_start.strftime("%H:%M"),
            "impact_window_end": post_end.strftime("%H:%M"),
        },
        "junction_impacts": junction_impacts,
        "timeline": timeline,
    }
